# Generated by Django 5.2.7 on 2025-10-16 15:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('conference_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(limit_value=30, message='la description doit contenir au minimum 30 caractères')])),
                ('location', models.CharField(max_length=50)),
                ('theme', models.CharField(choices=[('CS&IA', 'Computer science & IA'), ('CS', 'Social science'), ('SE', 'Science and eng')], max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('submission_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('abstract', models.TextField()),
                ('keyword', models.TextField()),
                ('paper', models.FileField(upload_to='sub_paper/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under review', 'Under review'), ('rejected', 'Rejected'), ('accepted', 'Accepted')], max_length=50)),
                ('payed', models.BooleanField(default=False)),
                ('submission_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='ConferenceApp.conference')),
            ],
        ),
    ]
